-- CREATE --

CREATE TABLE FUNCIONARIO(
    CPF VARCHAR(14),
    NOME VARCHAR(50),
    SALARIO FLOAT,
  	CARGO VARCHAR(30),
    CPF_CHEFE VARCHAR(14),
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CPF),
    CONSTRAINT FK_FUNCIONARIO_CPF_CHEFE FOREIGN KEY (CPF_CHEFE) REFERENCES FUNCIONARIO(CPF)
);

CREATE TABLE VISITANTE(
    CPF VARCHAR(14),
    NOME VARCHAR(50),
	  IDADE NUMBER(2),
	  ALTURA NUMBER(4, 3),
    CONSTRAINT PK_VISITANTE PRIMARY KEY(CPF)
);

CREATE TABLE PARQUE(
	NOME VARCHAR (14),
    CNPJ VARCHAR(14),
    HOR_ABERTURA INT,
    HOR_FECHAMENTO INT,
    ENTRADA NUMBER(4),
    END_CEP INT,
    END_NUM INT,
    TELEFONE1 INT,
    TELEFONE2 INT,
    CONSTRAINT PK_PARQUE PRIMARY KEY(CNPJ)
);

CREATE TABLE ATRACAO(
    CNPJ VARCHAR(14),
    NUM INT,
    TIPO VARCHAR(30),
    ALTURA_MIN NUMBER(4, 3),
    IDADE_MIN NUMBER(2),
    CAPACIDADE_MAX NUMBER(2),
    CPF_FUNC VARCHAR(14) UNIQUE NOT NULL, 
    CONSTRAINT PK_ATRACAO PRIMARY KEY(CNPJ, NUM),
    CONSTRAINT FK_ATRACAO_CNPJ_PARQUE FOREIGN KEY (CNPJ) REFERENCES PARQUE(CNPJ),
    CONSTRAINT FK_ATRACAO_CPF_FUNC FOREIGN KEY (CPF_FUNC) REFERENCES FUNCIONARIO(CPF)
);

CREATE TABLE FOOD_TRUCK(
  COD VARCHAR(10), 
  CATEGORIA VARCHAR(15),
  CONSTRAINT PK_FOOD_TRUCK PRIMARY KEY(COD) 
);

CREATE TABLE TRABALHA(
  CPF_FUNC VARCHAR(14),
  CNPJ VARCHAR(14),
  TURNO VARCHAR(10),
  CONSTRAINT PK_TRABALHA PRIMARY KEY(CPF_FUNC, CNPJ, TURNO),
  CONSTRAINT FK_FUNCIONARIO_TRABALHA FOREIGN KEY (CPF_FUNC) REFERENCES FUNCIONARIO(CPF),
  CONSTRAINT FK_TRABALHA_PARQUE FOREIGN KEY (CNPJ) REFERENCES PARQUE(CNPJ)
);

CREATE TABLE VISITA(
  CPF_VISITANTE VARCHAR(14),
  CNPJ VARCHAR(14),
  DATA DATE,
  CONSTRAINT PK_VISITA PRIMARY KEY(CPF_VISITANTE, CNPJ, DATA),
  CONSTRAINT FK_VISITA_VISITANTE FOREIGN KEY (CPF_VISITANTE) REFERENCES VISITANTE(CPF),
  CONSTRAINT FK_VISITA_PARQUE FOREIGN KEY (CNPJ) REFERENCES PARQUE(CNPJ)
);

CREATE TABLE TEM(
  CPF_FUNC VARCHAR(14),
  CNPJ VARCHAR(14),
  COD VARCHAR(10),
  CONSTRAINT PK_TEM PRIMARY KEY(CPF_FUNC, CNPJ, COD),
  CONSTRAINT FK_TEM_FUNCIONARIO FOREIGN KEY (CPF_FUNC) REFERENCES FUNCIONARIO(CPF),
  CONSTRAINT FK_TEM_PARQUE FOREIGN KEY (CNPJ) REFERENCES PARQUE(CNPJ),
  CONSTRAINT FK_TEM_FOOD_TRUCK FOREIGN KEY (COD) REFERENCES FOOD_TRUCK(COD)
);

CREATE TABLE PARTICIPA(
  CPF_VISITANTE VARCHAR(14),
  CNPJ VARCHAR(14),
  NUM INT,
  CONSTRAINT PK_PARTICIPA PRIMARY KEY(CPF_VISITANTE, CNPJ, NUM),
  CONSTRAINT FK_VISITANTE_PARTICIPA FOREIGN KEY (CPF_VISITANTE) REFERENCES VISITANTE(CPF),
  CONSTRAINT FK_PARTICIPA_ATRACAO FOREIGN KEY (CNPJ, NUM) REFERENCES ATRACAO(CNPJ, NUM)
);

CREATE TABLE PREMIO(
  ID VARCHAR(10), 
  NUM_TICKETS INT, 
  CPF_VISITANTE VARCHAR(14) NOT NULL, 
  CNPJ VARCHAR(14) NOT NULL, 
  NUM INT NOT NULL,
  CONSTRAINT PK_PREMIO PRIMARY KEY(ID),
  CONSTRAINT FK_PREMIO_PARTICIPA FOREIGN KEY(CPF_VISITANTE, CNPJ, NUM) REFERENCES PARTICIPA(CPF_VISITANTE, CNPJ, NUM)
);

CREATE TABLE COMPRA(
  CPF_VISITANTE VARCHAR(14),
  COD VARCHAR(10),
  NOTA_FISCAL VARCHAR(20),
  CONSTRAINT PK_COMPRA PRIMARY KEY(CPF_VISITANTE, COD, NOTA_FISCAL),
  CONSTRAINT FK_VISITANTE_COMPRA FOREIGN KEY (CPF_VISITANTE) REFERENCES VISITANTE(CPF),
  CONSTRAINT FK_COMPRA_FOOD_TRUCK FOREIGN KEY (COD) REFERENCES FOOD_TRUCK(COD)
);
